import random

def hangman():
    while True:
        print("""\nWelcome to Hangman Word Guessing Game
Press 1 to start the game
Press 2 to exit the game""")
        try:
            ch = int(input("Enter Your Choice: "))
        except ValueError:
            print("Please enter a valid number.")
            continue

        if ch == 1:
            words = [
                "apple", "house", "tiger", "green", "light", "phone", "dress", "pizza", "party", "music",
                "book", "movie", "smile", "happy", "train", "chair", "cloud", "beach", "night", "dance",
                "window", "bottle", "market", "jungle", "robot", "artist", "painter", "forest", "planet", "doctor",
                "silver", "dragon", "camera", "monkey", "wizard", "castle", "garden", "animal", "button", "mirror",
                "avalanche", "labyrinth", "skyscraper", "illusion", "knowledge", "elephant", "astronaut",
                "algorithm", "backpacker", "whirlwind", "oxygen", "penguin", "crocodile", "nightmare",
                "pharaoh", "suspense", "treadmill", "satellite", "triangle", "volcano", "democracy",
                "python", "binary", "magnet", "neuron", "nucleus", "galaxy", "friction", "voltage", "plasma", "carbon",
                "gravity", "isotope", "quantum", "circuit", "vector", "matrix", "compiler", "robot", "solar", "photon",
                "zelda", "pikachu", "batman", "thrones", "mario", "pacman", "spider", "joker", "tetris", "sonic",
                "desert", "island", "canada", "africa", "europe", "jungle", "london", "amazon", "everest", "village",
                "teacher", "pilot", "banker", "farmer", "actor", "writer", "lawyer", "singer", "dancer", "barber",
                "queue", "stack", "binary", "pointer", "python", "packet", "router", "syntax"
            ]

            word = random.choice(words)
            word_length = len(word)

            if word_length < 4:
                clues = 1
            elif word_length < 8:
                clues = 2
            else:
                clues = 3

            revealed_indexes = random.sample(range(word_length), clues)
            guessed_letters = [word[i] for i in revealed_indexes]

            lives = 6

            print("\n Game Started! Guess the word letter by letter.")
            print("Clue:", ' '.join([word[i] if i in revealed_indexes else '_' for i in range(word_length)]))
            print("Word has", word_length, "letters.")

            while True:
                print("\nCurrent Word:", ' '.join([char if char in guessed_letters else '_' for char in word]))
                print("Guessed Letters:", ' '.join(sorted(guessed_letters)))
                print("Lives Left:", lives)

                guess = input("Enter your guess letter: ").lower()

                if not guess.isalpha() or len(guess) != 1:
                    print("Please enter a single valid letter.")
                    continue

                if guess in guessed_letters:
                    print("You already guessed that letter.")
                    continue

                guessed_letters.append(guess)
                if guess in word:
                    print("Correct guess!")
                    if lives == 6:
                        print("""Stage 0
..|...
......
......
......
......
......""")
                    elif lives == 5:
                        print(""" Stage 1
..|...
..O...
......
......
......
......""")

                    elif lives == 4:
                        print("""Stage 2
..|...
..O...
..|...
......
......
......""")
                    elif lives == 3:
                        print("""Stage 3 
..|...
..O...
./|...
......
......
......""")
                    elif lives == 2:
                        print("""Stage 4
..|...
..O...
./|\..
......
......
......""")
                    elif lives == 1:
                        print("""Stage 5
..|...
..O...
./|\..
./....
......
......""")
                else:
                    lives -= 1
                    print("Wrong guess!")
                    if lives == 6:
                        print("""Stage 0
..|...
......
......
......
......
......""")
                    elif lives == 5:
                        print(""" Stage 1
..|...
..O...
......
......
......
......""")

                    elif lives == 4:
                        print("""Stage 2
..|...
..O...
..|...
......
......
......""")
                    elif lives == 3:
                        print("""Stage 3 
..|...
..O...
./|...
......
......
......""")
                    elif lives == 2:
                        print("""Stage 4
..|...
..O...
./|\..
......
......
......""")
                    elif lives == 1:
                        print("""Stage 5
..|...
..O...
./|\..
./....
......
......""")

                current_clue = ''.join([char if char in guessed_letters else '_' for char in word])

                if '_' not in current_clue:
                    print("\nCongratulations! You guessed the word:", word)
                    break

                if lives == 0:
                    print("""Game Over! You are dead!!! The word was:""", word)
                    print("""Stage 6
......
..O...
./|\..
./ \..
......
......""")
                    break

        elif ch == 2:
            print("Exiting game. Goodbye!")
            break
        else:
            print("Invalid Choice! Please enter 1 or 2.")

hangman()